import '@/assets/styles/globals.scss';
import { ArticlesProvider } from '@/contexts/ArticleContext/ArticleContextProvider';
import { SearchProvider } from '@/contexts/SearchContext/SearchContextProvider';
import { ThemeProvider } from '@/contexts/ThemeContext/ThemeContextProvide';
import Header from '@/features/Header/Header';
import type { Metadata } from 'next';
import { Montserrat } from 'next/font/google';

const monserrat = Montserrat({
  subsets: ['latin'],
  weight: ['400', '700'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en'>
      <body className={monserrat.className}>
        <ArticlesProvider>
         <ThemeProvider>
          <SearchProvider>
            <Header />
            {children}
          </SearchProvider>
         </ThemeProvider>
        </ArticlesProvider>
      </body>
    </html>
  );
}
